# Generated by Django 5.2.9 on 2025-12-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('user_phone', models.CharField(max_length=11)),
                ('region', models.CharField(max_length=4)),
            ],
        ),
    ]
