# Generated by Django 5.2.9 on 2025-12-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='clients/')),
                ('passport_first_name', models.CharField(max_length=100)),
                ('passport_last_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_expiry_date', models.DateField()),
                ('passport_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('tax_number', models.CharField(max_length=50)),
                ('authorized_phone', models.CharField(max_length=20)),
                ('authorized_email', models.EmailField(max_length=254)),
                ('services', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='kullanici',
        ),
    ]
