# Generated by Django 5.2.9 on 2025-12-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_provider_delete_kullanici'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
