# Generated by Django 5.2.9 on 2025-12-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='password',
        ),
    ]
