# Generated by Django 5.2.9 on 2025-12-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_client_password_remove_provider_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
    ]
