# Generated by Django 5.2.9 on 2025-12-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
